#!/usr/bin/env python2

import sys
import tango

if len(sys.argv) < 4:
    print("usage: {} <hostname> <level> <exec>/<inst>...".format(sys.argv[0]))
    sys.exit(1)

host = sys.argv[1]
level = sys.argv[2]

def add_server(name):
    info = tango.DbServerInfo()
    info.name = name.lower()
    info.host = host
    info.mode = 1 # controlled
    info.level = int(level)

    export = tango.DbDevExportInfo()
    export.name = "dserver/{}".format(name)
    export.ior = 'nada'
    export.host = host
    export.version = '0'
    export.pid = -1

    db = tango.Database()
    db.put_server_info(info)
    db.export_device(export)
    db.unexport_device(export.name)

failed = False

for name in sys.argv[3:]:
    try:
        add_server(name)
    except:
        failed = True
        print("failed: {}".format(name))

if failed:
    sys.exit(1)
